# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8a5eb73bbaf7d1053278ad9f5ec39756c081ca07c29bf95e85bc6752f67d4a07f835e506a6b05fa42f71685af58f43eb90b706b50abfb58da849dd19a1030da

test:
  secret_key_base: 78b3ce1abd4d2621b54cb0f712455fa201cf86fbf0ca5373113373526e0dbee471519aa941017a102ce14ec17236504d24bf495af7a26656ffa32a28190856f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
